# Your Name or Company
title: Michael VanDyke

# Description of your website. This is used for social sharing.
description: iOS nerd, lifetime student, technologist, and hobbiest mechanic.

# A brief blurb about yourself
content: iOS nerd, lifetime student, technologist, and hobbiest mechanic. Check me out!

# Add your social links
social:
  - platform: linkedin
    url: https://www.linkedin.com/in/mjvandyke/
  - platform: github
    url: https://github.com/codethebeard
  - platform: instagram
    url: https://www.instagram.com/codethebeard/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
