# Your Name or Company
title: Michael VanDyke

# Description of your website. This is used for social sharing.
description: Engineering lead, lifetime student, and professional amateur of making things.

# A brief blurb about yourself
content: Engineering lead, lifetime student, and professional amateur of making things.

# Add your social links
social:
  - platform: linkedin
    url: https://www.linkedin.com/in/mjvandyke/
  - platform: github
    url: https://github.com/codethebeard
  - platform: instagram
    url: https://www.instagram.com/codethebeard/

# General settings
markdown: kramdown
sharing_image: share.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
